import java.util.Arrays;

/**
 * @author shanhq96@gmail.com
 * @ClassName 389_Find the Difference
 * @Description Given two strings s and t which consist of only lowercase letters.
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 * Example:
 * Input:
 * s = "abcd"
 * t = "abcde"
 * Output:
 * e
 * Explanation:
 * 'e' is the letter that was added.
 * @date 2017/4/6-8:10
 */
public class Solution {
    /**
     *异或所有字符  8ms
     */
    public char findTheDifference(String s, String t) {
        char c = 0;
        int n = s.length();
        c ^= t.charAt(n);
        for (n = n - 1; n >= 0; n--) {
            c^=s.charAt(n);
            c^=t.charAt(n);
        }
        return c;
    }


    /**
     计算2个字符串的ascii值合,然后求差值  8ms
     public char findTheDifference(String s, String t){
     int sAsciiSum = 0;
     int tAsciiSum = 0;
     int i = 0;
     for (;i<s.length();i++){
     sAsciiSum += (int)s.charAt(i);
     tAsciiSum += (int)t.charAt(i);
     }
     tAsciiSum += (int)t.charAt(i);
     return (char)(tAsciiSum - sAsciiSum);
     }
     */
    /*
    计算  13ms
    public char findTheDifference(String s, String t) {
        char[] sArray = s.toCharArray();
        char[] tArray = t.toCharArray();
        Arrays.sort(sArray);
        Arrays.sort(tArray);
        int i = 0;
        for (; i < sArray.length; i++) {
            if (sArray[i] != tArray[i]){
                break;
            }
        }
        return tArray[i];
    }*/
}